version: '3'
services:
  redis:
    image: "redis:5.0.4-alpine"

  backend:
    image: "mojaloop/sdk-mock-dfsp-backend"
    env_file: ./backend.env
    ports:
      - "3000:3000"
    depends_on:
      - scheme-adapter

  scheme-adapter:
    image: "mojaloop/sdk-scheme-adapter:latest"
    env_file: ./scheme-adapter.env
    ports:
      - "4000:4000"
    depends_on:
      - redis
